# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('remainCnt', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=1000)),
                ('mail', models.TextField(default='', max_length=1000)),
                ('contactPerson', models.TextField(default='', max_length=1000)),
                ('tel', models.TextField(default='', max_length=40)),
                ('comment', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
