# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '0002_auto_20170305_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('remainCnt', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MoveStandartWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('remainCnt', models.IntegerField(default=0)),
                ('standartWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructors.StandartWork')),
            ],
        ),
    ]
