# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movestandartwork',
            name='standartWork',
        ),
        migrations.DeleteModel(
            name='MoveStandartWork',
        ),
    ]
