# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0002_stockstruct_area'),
        ('stock', '0002_auto_20170227_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraditionAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.AssemblyUnit')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraditionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraditionEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='extradition',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Extradition',
        ),
    ]
