# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170508_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=1000)),
                ('mail', models.TextField(default='', max_length=1000)),
                ('contactPerson', models.TextField(default='', max_length=1000)),
                ('tel', models.TextField(default='', max_length=40)),
                ('comment', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
