# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170302_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraditionassembly',
            old_name='equipment',
            new_name='assembly',
        ),
    ]
