# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0003_auto_20170302_0758'),
        ('stock', '0004_auto_20170302_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.AssemblyUnit')),
            ],
        ),
        migrations.CreateModel(
            name='MoveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='MoveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cnt', models.IntegerField(default=0)),
                ('flgAcceptance', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='extraditionassembly',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='extraditiondetail',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='extraditionequipment',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='ExtraditionAssembly',
        ),
        migrations.DeleteModel(
            name='ExtraditionDetail',
        ),
        migrations.DeleteModel(
            name='ExtraditionEquipment',
        ),
    ]
