# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20170302_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveassembly',
            name='remainCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movedetail',
            name='remainCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moveequipment',
            name='remainCnt',
            field=models.IntegerField(default=0),
        ),
    ]
