# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_movestandartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movestandartwork',
            name='standartWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.StandartWork'),
        ),
    ]
