# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0003_auto_20170508_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchoose',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookChoose',
        ),
    ]
