# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '__first__'),
        ('plan', '0001_initial'),
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.ManyToManyField(blank=True, null=True, to='constructors.NeedStruct')),
            ],
        ),
        migrations.CreateModel(
            name='StockReportStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getCnt', models.FloatField(default=0)),
                ('rejectCnt', models.FloatField(default=0)),
                ('dustCnt', models.FloatField(default=0)),
                ('returnCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=b'', max_length=2000, null=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('rationale', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Rationale')),
                ('scheme', models.ManyToManyField(blank=True, default=None, null=True, to='plan.Scheme')),
                ('standartWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.StandartWork')),
                ('workPlace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.WorkPlace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField(default=datetime.date.today)),
                ('VIKDate', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, default=b'', max_length=10000, null=True)),
                ('flgCalculateEquipment', models.BooleanField(default=False)),
                ('flgCalculateWorkers', models.BooleanField(default=False)),
                ('needVIK', models.BooleanField(default=False)),
                ('VIKer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VIKER_name', to='plan.Worker', verbose_name=b'\xd0\x92\xd0\x98\xd0\x9a')),
                ('factWorkPart', models.ManyToManyField(blank=True, null=True, related_name='fact_WorkPart', to='workReport.WorkPart')),
                ('noPlanHardware', models.ManyToManyField(blank=True, null=True, related_name='no_PlanHardware_name', to='workReport.StockReportStruct', verbose_name=b'\xd0\x92\xd0\xbd\xd0\xb5\xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('planHardware', models.ManyToManyField(blank=True, null=True, related_name='planHardware_name', to='workReport.StockReportStruct', verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f')),
                ('rejected', models.ManyToManyField(blank=True, null=True, to='workReport.Reject')),
                ('reportChecker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportChecker_name', to='plan.Worker', verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x8f\xd1\x8e\xd1\x89\xd0\xb8\xd0\xb9 \xd0\xbe\xd1\x82\xd1\x87\xd1\x91\xd1\x82')),
                ('reportMaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportMaker_name', to='plan.Worker', verbose_name=b'C\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xbe\xd1\x82\xd1\x87\xd1\x91\xd1\x82\xd0\xb0')),
                ('stockMan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockMan_name', to='plan.Worker', verbose_name=b'\xd0\x9a\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xbe\xd0\xb2\xd1\x89\xd0\xb8\xd0\xba')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_name', to='plan.Worker', verbose_name=b'\xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')),
                ('workPart', models.ManyToManyField(blank=True, null=True, related_name='work_Part', to='workReport.WorkPart')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_name', to='plan.Worker', verbose_name=b'\xd0\x98c\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')),
            ],
        ),
    ]
