# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nop', '0001_initial'),
        ('plan', '0002_auto_20170519_1603'),
        ('constructors', '0002_equipment_providers'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.ManyToManyField(blank=True, to='constructors.NeedStruct')),
            ],
        ),
        migrations.CreateModel(
            name='StockReportStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('getCnt', models.FloatField(default=0)),
                ('rejectCnt', models.FloatField(default=0)),
                ('dustCnt', models.FloatField(default=0)),
                ('returnCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('rationale', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Rationale')),
                ('scheme', models.ManyToManyField(blank=True, default=None, to='constructors.Scheme')),
                ('standartWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
                ('workPlace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nop.WorkPlace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField(default=datetime.date.today)),
                ('VIKDate', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('flgCalculateEquipment', models.BooleanField(default=False)),
                ('flgCalculateWorkers', models.BooleanField(default=False)),
                ('needVIK', models.BooleanField(default=False)),
                ('area', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('VIKer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VIKER_name', to='nop.Worker', verbose_name='ВИК')),
                ('factWorkPart', models.ManyToManyField(blank=True, related_name='fact_WorkPart', to='workReport.WorkPart')),
                ('noPlanHardware', models.ManyToManyField(blank=True, related_name='no_PlanHardware_name', to='workReport.StockReportStruct', verbose_name='Внеплановая')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('planHardware', models.ManyToManyField(blank=True, related_name='planHardware_name', to='workReport.StockReportStruct', verbose_name='Плановая')),
                ('rejected', models.ManyToManyField(blank=True, to='workReport.Reject')),
                ('reportChecker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportChecker_name', to='nop.Worker', verbose_name='Проверяющий отчёт')),
                ('reportMaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportMaker_name', to='nop.Worker', verbose_name='Cоставитель отчёта')),
                ('stockMan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockMan_name', to='nop.Worker', verbose_name='Кладовщик')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_name', to='nop.Worker', verbose_name='Руководитель')),
                ('workPart', models.ManyToManyField(blank=True, related_name='work_Part', to='workReport.WorkPart')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_name', to='nop.Worker', verbose_name='Иcполнитель')),
            ],
        ),
    ]
