# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 20:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=100)),
                ('fullWorkPos', models.IntegerField(default=0)),
                ('assemblyUnits', models.ManyToManyField(related_name='_assemblyunits_assemblyUnits_+', to='workReport.AssemblyUnits')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('fullWorkPos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('hardwareType', models.IntegerField(default=0)),
                ('dimension', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FullStandartWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('quequepos', models.IntegerField(default=0)),
                ('comment', models.CharField(default=b'', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedCnt', models.FloatField(default=0)),
                ('getCnt', models.FloatField(default=0)),
                ('rejectCnt', models.FloatField(default=0)),
                ('dustCnt', models.FloatField(default=0)),
                ('remainCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dimension', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default=b'', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('needVP', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=10000)),
                ('status', models.IntegerField(default=0)),
                ('startDate', models.DateField(verbose_name=b'date start')),
                ('agreementDate', models.DateField(verbose_name=b'date agreement')),
                ('planDate', models.DateField(verbose_name=b'date plan')),
                ('fullWorkPos', models.IntegerField(default=0)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Agreement')),
                ('assemblyUnits', models.ManyToManyField(to='workReport.AssemblyUnits')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Customer')),
                ('details', models.ManyToManyField(to='workReport.Detail')),
                ('equipment', models.ManyToManyField(to='workReport.Equipment')),
                ('fullWorks', models.ManyToManyField(to='workReport.FullStandartWork')),
                ('materials', models.ManyToManyField(to='workReport.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Rationale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StandartWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('duration', models.FloatField(default=0)),
                ('hardwareEquipment', models.ManyToManyField(blank=True, default=None, null=True, to='workReport.HardwareEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='TehReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TehUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=1000)),
                ('assemblyUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.AssemblyUnits')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Detail')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.Material')),
                ('nextUnits', models.ManyToManyField(related_name='_tehunit_nextUnits_+', to='workReport.TehUnit')),
                ('standartWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.StandartWork')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.IntegerField(default=0)),
                ('tnumber', models.IntegerField()),
                ('patronymic', models.CharField(max_length=200)),
                ('attestation', models.ManyToManyField(blank=True, to='workReport.Attestation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=b'', max_length=2000, null=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('rationale', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Rationale')),
                ('standartWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.StandartWork')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField(default=datetime.date.today)),
                ('VIKDate', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, default=b'', max_length=10000, null=True)),
                ('flgCalculateEquipment', models.BooleanField(default=False)),
                ('VIKer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VIKER_name', to='workReport.Worker', verbose_name=b'\xd0\x92\xd0\x98\xd0\x9a')),
                ('factWorkPart', models.ManyToManyField(blank=True, null=True, related_name='fact_WorkPart', to='workReport.WorkPart')),
                ('noPlanHardware', models.ManyToManyField(blank=True, null=True, related_name='no_PlanHardware_name', to='workReport.HardwareEquipment', verbose_name=b'\xd0\x92\xd0\xbd\xd0\xb5\xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Order')),
                ('planHardware', models.ManyToManyField(blank=True, null=True, related_name='planHardware_name', to='workReport.HardwareEquipment', verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f')),
                ('rejected', models.ManyToManyField(blank=True, null=True, to='workReport.Reject')),
                ('reportChecker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportChecker_name', to='workReport.Worker', verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x8f\xd1\x8e\xd1\x89\xd0\xb8\xd0\xb9 \xd0\xbe\xd1\x82\xd1\x87\xd1\x91\xd1\x82')),
                ('reportMaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportMaker_name', to='workReport.Worker', verbose_name=b'C\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xbe\xd1\x82\xd1\x87\xd1\x91\xd1\x82\xd0\xb0')),
                ('stockMan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockMan_name', to='workReport.Worker', verbose_name=b'\xd0\x9a\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xbe\xd0\xb2\xd1\x89\xd0\xb8\xd0\xba')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_name', to='workReport.Worker', verbose_name=b'\xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')),
                ('workPart', models.ManyToManyField(blank=True, null=True, related_name='work_Part', to='workReport.WorkPart')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_name', to='workReport.Worker', verbose_name=b'\xd0\x98c\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')),
            ],
        ),
        migrations.AddField(
            model_name='workpart',
            name='workPlace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.WorkPlace'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ManyToManyField(to='workReport.WorkerPosition'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tehreview',
            name='firstUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.TehUnit'),
        ),
        migrations.AddField(
            model_name='standartwork',
            name='positionsEnable',
            field=models.ManyToManyField(to='workReport.WorkerPosition'),
        ),
        migrations.AddField(
            model_name='order',
            name='tehReview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.TehReview'),
        ),
        migrations.AddField(
            model_name='hardwareequipment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Material'),
        ),
        migrations.AddField(
            model_name='fullstandartwork',
            name='standartWork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workReport.StandartWork'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='workReport.Material'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='scheme',
            field=models.ManyToManyField(blank=True, null=True, to='workReport.Scheme'),
        ),
        migrations.AddField(
            model_name='detail',
            name='equipment',
            field=models.ManyToManyField(to='workReport.Equipment'),
        ),
        migrations.AddField(
            model_name='detail',
            name='fullWorks',
            field=models.ManyToManyField(to='workReport.FullStandartWork'),
        ),
        migrations.AddField(
            model_name='detail',
            name='materials',
            field=models.ManyToManyField(to='workReport.Material'),
        ),
        migrations.AddField(
            model_name='detail',
            name='scheme',
            field=models.ManyToManyField(to='workReport.Scheme'),
        ),
        migrations.AddField(
            model_name='assemblyunits',
            name='details',
            field=models.ManyToManyField(to='workReport.Detail'),
        ),
        migrations.AddField(
            model_name='assemblyunits',
            name='equipment',
            field=models.ManyToManyField(to='workReport.Equipment'),
        ),
        migrations.AddField(
            model_name='assemblyunits',
            name='fullWorks',
            field=models.ManyToManyField(to='workReport.FullStandartWork'),
        ),
        migrations.AddField(
            model_name='assemblyunits',
            name='materials',
            field=models.ManyToManyField(to='workReport.Material'),
        ),
        migrations.AddField(
            model_name='assemblyunits',
            name='scheme',
            field=models.ManyToManyField(to='workReport.Scheme'),
        ),
    ]
