# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170227_1315'),
        ('workReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstruct',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plan.Area'),
            preserve_default=False,
        ),
    ]
