# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0002_auto_20170305_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='needs',
            field=models.ManyToManyField(blank=True, to='constructors.NeedStruct'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='factWorkPart',
            field=models.ManyToManyField(blank=True, related_name='fact_WorkPart', to='workReport.WorkPart'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='noPlanHardware',
            field=models.ManyToManyField(blank=True, related_name='no_PlanHardware_name', to='workReport.StockReportStruct', verbose_name=b'\xd0\x92\xd0\xbd\xd0\xb5\xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='planHardware',
            field=models.ManyToManyField(blank=True, related_name='planHardware_name', to='workReport.StockReportStruct', verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='rejected',
            field=models.ManyToManyField(blank=True, to='workReport.Reject'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='workPart',
            field=models.ManyToManyField(blank=True, related_name='work_Part', to='workReport.WorkPart'),
        ),
    ]
