# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0002_auto_20170224_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='flgCalculateEquipment',
            field=models.BooleanField(default=False),
        ),
    ]
