# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170227_1315'),
        ('workReport', '0004_remove_detail_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyunit',
            name='assemblyUnits',
        ),
        migrations.RemoveField(
            model_name='assemblyunit',
            name='equipment',
        ),
        migrations.AddField(
            model_name='workpart',
            name='scheme',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='plan.Scheme'),
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='code',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='scheme',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='plan.Scheme'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='scheme',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='plan.Scheme'),
        ),
    ]
