# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0005_auto_20170302_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyunit',
            name='needVIK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='needVIK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='needVIK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standartwork',
            name='needVIK',
            field=models.BooleanField(default=False),
        ),
    ]
