# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0005_auto_20170425_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
