# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0006_auto_20170302_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyunit',
            name='code',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='code',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
    ]
