# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0006_workreport_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
