# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20170303_0811'),
        ('workReport', '0007_auto_20170303_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyunit',
            name='needStruct',
        ),
        migrations.RemoveField(
            model_name='assemblyunit',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='assemblyunit',
            name='stockStruct',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='needStruct',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stockStruct',
        ),
        migrations.RemoveField(
            model_name='needstruct',
            name='assemblyUnit',
        ),
        migrations.RemoveField(
            model_name='needstruct',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='stockreportstruct',
            name='assemblyUnit',
        ),
        migrations.RemoveField(
            model_name='stockreportstruct',
            name='detail',
        ),
        migrations.DeleteModel(
            name='AssemblyUnit',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
