# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workReport', '0009_auto_20170304_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='needStructStandartWork12', to='workReport.NeedStruct'),
        ),
        migrations.AlterField(
            model_name='needstruct',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.Equipment'),
        ),
        migrations.AlterField(
            model_name='needstruct',
            name='standartWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workReport.StandartWork'),
        ),
    ]
