# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('nop', '0001_initial'),
        ('constructors', '0002_equipment_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=100000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nop.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEquipmentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planCnt', models.FloatField(default=1)),
                ('curCnt', models.FloatField(default=0)),
                ('sDate', models.DateField(default=datetime.datetime(2017, 5, 19, 16, 19, 14, 5297))),
                ('pDate', models.DateField(default=datetime.datetime(2017, 5, 19, 16, 19, 14, 5297))),
                ('fDate', models.DateField(default=datetime.datetime(2017, 5, 19, 16, 19, 14, 5297))),
                ('complete', models.BooleanField(default=False)),
                ('canEdit', models.BooleanField(default=True)),
                ('cooperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Provider')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
                ('excuses', models.ManyToManyField(blank=True, null=True, to='zgi.Excuse')),
                ('workPlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nop.WorkPlace')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nop.Worker')),
            ],
            options={
                'ordering': ['pDate'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100000, null=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nop.Worker')),
                ('peParts', models.ManyToManyField(blank=True, null=True, to='zgi.PlanEquipmentPart')),
            ],
        ),
    ]
