# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgi', '0008_auto_20170519_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planequipmentpart',
            name='fDate',
            field=models.DateField(default=datetime.datetime(2017, 5, 19, 17, 10, 11, 391498)),
        ),
        migrations.AlterField(
            model_name='planequipmentpart',
            name='pDate',
            field=models.DateField(default=datetime.datetime(2017, 5, 19, 17, 10, 11, 391498)),
        ),
        migrations.AlterField(
            model_name='planequipmentpart',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2017, 5, 19, 17, 10, 11, 391498)),
        ),
    ]
