# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zgi', '0010_auto_20170519_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='planequipmentpart',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planequipmentpart',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planequipmentpart',
            name='fDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planequipmentpart',
            name='pDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planequipmentpart',
            name='sDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
