# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgi', '0011_auto_20170519_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='planequipmentpart',
            name='needVIK',
            field=models.BooleanField(default=False),
        ),
    ]
