# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=100)),
                ('contactPerson', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=100000, null=True)),
                ('subText', models.TextField(blank=True, max_length=100000, null=True)),
                ('appendText', models.TextField(blank=True, max_length=100000, null=True)),
                ('caption', models.TextField(blank=True, max_length=100000, null=True)),
                ('pageName', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('needVP', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=10000)),
                ('status', models.IntegerField(default=0)),
                ('startDate', models.DateField(verbose_name='date start')),
                ('agreementDate', models.DateField(verbose_name='date agreement')),
                ('planDate', models.DateField(verbose_name='date plan')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Agreement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rationale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
