# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='privilege',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='worker',
            name='attestation',
            field=models.ManyToManyField(to='plan.Attestation'),
        ),
    ]
