# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='agreementDate',
            field=models.DateField(verbose_name='date agreement'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='planDate',
            field=models.DateField(verbose_name='date plan'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='startDate',
            field=models.DateField(verbose_name='date start'),
        ),
    ]
