# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='code',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Worker'),
        ),
    ]
