# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170126_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
