# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170126_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandartWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('positionsEnable', models.ManyToManyField(to='plan.WorkerPosition')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('comment', models.CharField(max_length=2000)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('standartWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.StandartWork')),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.AlterField(
            model_name='worker',
            name='privilege',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workreport',
            name='factWorkPart',
            field=models.ManyToManyField(related_name='fact_WorkPart', to='plan.WorkPart'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='workPart',
            field=models.ManyToManyField(related_name='work_Part', to='plan.WorkPart'),
        ),
    ]
