# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170126_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywork',
            name='workPlace',
        ),
        migrations.AddField(
            model_name='workpart',
            name='workPlace',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='plan.WorkPlace'),
        ),
        migrations.DeleteModel(
            name='DailyWork',
        ),
    ]
