# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170126_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='reportChecker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reportChecker_name', to='plan.Worker', verbose_name='Проверяющий отчёт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workreport',
            name='reportMaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reportMaker_name', to='plan.Worker', verbose_name='Cоставитель отчёта'),
            preserve_default=False,
        ),
    ]
