# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20170126_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workreport',
            old_name='date',
            new_name='adate',
        ),
    ]
