# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20170126_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='VIKDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='adate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
