# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nop', '0002_auto_20170519_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nop.Area'),
        ),
    ]
