# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nop', '0004_auto_20170519_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nop.Area'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='wpos',
            field=models.ManyToManyField(to='nop.WorkerPosition'),
        ),
    ]
