# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('dimension', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('equipmentType', models.IntegerField(default=0)),
                ('needVIK', models.BooleanField(default=False)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NeedStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('completeCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nop.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='StockStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nop.Area')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='genEquipment',
            field=models.ManyToManyField(blank=True, default=None, related_name='genEquipment12', to='constructors.NeedStruct'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, related_name='needStructStandartWork12', to='constructors.NeedStruct'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='scheme',
            field=models.ManyToManyField(blank=True, null=True, to='constructors.Scheme'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='stockStruct',
            field=models.ManyToManyField(blank=True, default=None, to='constructors.StockStruct'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='worplaces',
            field=models.ManyToManyField(blank=True, default=None, to='nop.WorkPlace'),
        ),
    ]
