# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('dimension', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('equipmentType', models.IntegerField(default=0)),
                ('needVIK', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NeedStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('completeCnt', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='StandartWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('duration', models.FloatField(default=0)),
                ('needVIK', models.BooleanField(default=False)),
                ('needStruct', models.ManyToManyField(blank=True, default=None, null=True, related_name='needStructStandartWork', to='constructors.NeedStruct')),
                ('positionsEnable', models.ManyToManyField(to='plan.WorkerPosition')),
            ],
        ),
        migrations.CreateModel(
            name='StockStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Area')),
            ],
        ),
        migrations.AddField(
            model_name='needstruct',
            name='standartWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructors.StandartWork'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='needStructStandartWork12', to='constructors.NeedStruct'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='scheme',
            field=models.ManyToManyField(blank=True, null=True, to='plan.Scheme'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='stockStruct',
            field=models.ManyToManyField(blank=True, null=True, to='constructors.StockStruct'),
        ),
    ]
