# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, related_name='needStructStandartWork12', to='constructors.NeedStruct'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='scheme',
            field=models.ManyToManyField(blank=True, to='plan.Scheme'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stockStruct',
            field=models.ManyToManyField(blank=True, default=None, to='constructors.StockStruct'),
        ),
        migrations.AlterField(
            model_name='needstruct',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='constructors.Equipment'),
        ),
        migrations.AlterField(
            model_name='needstruct',
            name='standartWork',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='constructors.StandartWork'),
        ),
        migrations.AlterField(
            model_name='standartwork',
            name='needStruct',
            field=models.ManyToManyField(blank=True, default=None, related_name='needStructStandartWork', to='constructors.NeedStruct'),
        ),
    ]
