# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_equipment_providers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='worplaces',
            new_name='workPlaces',
        ),
    ]
