# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_auto_20170305_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
