# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0003_equipment_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('equipment', models.ManyToManyField(to='constructors.Equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='standartwork',
            name='needStruct',
        ),
        migrations.RemoveField(
            model_name='standartwork',
            name='positionsEnable',
        ),
        migrations.RemoveField(
            model_name='needstruct',
            name='standartWork',
        ),
        migrations.DeleteModel(
            name='StandartWork',
        ),
    ]
