# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0006_equipment_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
