# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0007_auto_20170509_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='genEquipment',
            field=models.ManyToManyField(blank=True, default=None, related_name='genEquipment12', to='constructors.NeedStruct'),
        ),
    ]
