# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '0002_equipment_providers'),
        ('plan', '0002_auto_20170519_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('needVP', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=10000)),
                ('status', models.IntegerField(default=0)),
                ('startDate', models.DateField(verbose_name='date start')),
                ('agreementDate', models.DateField(verbose_name='date agreement')),
                ('planDate', models.DateField(verbose_name='date plan')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Agreement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Customer')),
                ('needStruct', models.ManyToManyField(blank=True, default=None, to='constructors.NeedStruct')),
            ],
        ),
    ]
